// src/mfe-archetype/files/angular/routing/fe-obe-__name@dasherize__/src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { RoutingService } from '../services/routing.service';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  constructor(private routingService: RoutingService) {}

  public navigate(path: string): void {
    this.routingService.navigate(path);
  }

  ngOnInit(): void {}
}

<mat-card class="example-card">
  <mat-card-header>
    <div mat-card-avatar class="example-header-image"></div>
    <mat-card-title>Supervielle</mat-card-title>
    <mat-card-subtitle>Home</mat-card-subtitle>
  </mat-card-header>
  <img mat-card-image src="https://bancosporinternet.com.ar/wp-content/uploads/2020/10/Banco-Supervielle-Home-Banking.jpg" alt="Photo of a Shiba Inu">
  <mat-card-content>
    <p>
      Banco Supervielle es un entidad bancaria comercial de origen argentino, con sede en Buenos Aires. Supervielle surge de la fusión de Banco Banex y Société Générale de Argentina
    </p>
  </mat-card-content>
  <mat-card-actions>
    <button mat-button (click)="navigate('/<%= route %>/page')">PAGE</button>
  </mat-card-actions>
</mat-card>

// src/mfe-archetype/files/react/routing/__name@dasherize__/src/components/Home.js
import React from "react";
import { makeStyles } from "@material-ui/core/styles";
import Card from "@material-ui/core/Card";
import CardHeader from "@material-ui/core/CardHeader";
import CardMedia from "@material-ui/core/CardMedia";
import CardContent from "@material-ui/core/CardContent";
import CardActions from "@material-ui/core/CardActions";
import Avatar from "@material-ui/core/Avatar";
import Typography from "@material-ui/core/Typography";
import { Link as RouterLink } from "react-router-dom";
import Button from "@material-ui/core/Button";

const useStyles = makeStyles((theme) => ({
  root: {
    maxWidth: 345,
  },
  media: {
    height: 0,
    paddingTop: "56.25%", // 16:9
  },
  expand: {
    transform: "rotate(0deg)",
    marginLeft: "auto",
    transition: theme.transitions.create("transform", {
      duration: theme.transitions.duration.shortest,
    }),
  },
  expandOpen: {
    transform: "rotate(180deg)",
  },
  avatar: {
    backgroundSize: "cover",
  },
}));

export default () => {
  const classes = useStyles();
  return (
    <Card className={classes.root}>
      <CardHeader
        avatar={
          <Avatar
            src="https://pbs.twimg.com/profile_images/922849160826470400/PWLsCRyX_400x400.jpg"
            className={classes.avatar}
          />
        }
        title="Supervielle"
        subheader="Home"
      />
      <CardMedia
        className={classes.media}
        image="https://bancosporinternet.com.ar/wp-content/uploads/2020/10/Banco-Supervielle-Home-Banking.jpg"
        title="Supervielle"
      />
      <CardContent>
        <Typography variant="body2" color="textSecondary" component="p">
          Banco Supervielle es un entidad bancaria comercial de origen
          argentino, con sede en Buenos Aires. Supervielle surge de la fusión de
          Banco Banex y Société Générale de Argentina
        </Typography>
      </CardContent>
      <CardActions disableSpacing>
        <RouterLink style={{ textDecoration: "none" }} to="/<%= name %>/page">
          <Button variant="contained" size="small">
            Page
          </Button>
        </RouterLink>
      </CardActions>
    </Card>
  );
};
